In [ ]:
#pytorch features
# 1 tensor computation
# 2 gpu accelaration
# 3 dyanamic compuation graph
# 4 automatic differentiation
# 5 distributed training
# 6 interoperability with other libraries

In [ ]:
#tensors is a specialized multi dimensional array designed for mathematical and computational efficiency

In [ ]:
import torch
print(torch.__version__)

2.10.0+cpu


In [ ]:
#checking is gpu is available or not
if torch.cuda.is_available() :
  print("gpu is available")
  print(f"using gpu :{torch.cuda.get_device_name(0)}")

else:
  print("gpu not available")

gpu not available


# CREATING TENSOR

In [ ]:
t = torch.empty(2,3)
print(t)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#checking type
type(t)

torch.Tensor

In [ ]:
print(torch.zeros(2,3))
print(torch.ones(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
torch.rand(2,3)

tensor([[0.1592, 0.7763, 0.5338],
        [0.2181, 0.4645, 0.5213]])

In [ ]:
#using manual seed to print rand values same when run on any pc anytime
torch.manual_seed(5)
print(torch.rand(2,3))

tensor([[0.8303, 0.1261, 0.9075],
        [0.8199, 0.9201, 0.1166]])


In [ ]:
torch.manual_seed(5)
print(torch.rand(2,3))

tensor([[0.8303, 0.1261, 0.9075],
        [0.8199, 0.9201, 0.1166]])


In [ ]:
#manually making tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x = torch.tensor([[1,2,9],[4,5,6]])
print(x)
print(x.shape)

tensor([[1, 2, 9],
        [4, 5, 6]])
torch.Size([2, 3])


In [ ]:
# if we want to make a new tensor of same size of previously defined tensor
y = torch.empty_like(x)
print(y)
v = torch.rand_like(x,dtype=float)
print(v)


tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0.3151, 0.2661, 0.8514],
        [0.5793, 0.7200, 0.8474]], dtype=torch.float64)


In [ ]:
#just checking type
print(x.dtype)
print(y.dtype)
print(v.dtype)

torch.int64
torch.int64
torch.float64


In [ ]:
#asssign dtype while creating tensor
torch.tensor([0.2,4.3,5.6,0.7],dtype=int)

tensor([0, 4, 5, 0])

In [ ]:
#changing dtype of existing tensor
v = v.to(torch.int)
print(v)
print(v.dtype)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.int32


In [ ]:
# mathematica operations
print(v+2)
print(v*2)
print(v//2)
print(v-2)

tensor([[2, 2, 2],
        [2, 2, 2]], dtype=torch.int32)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[-2, -2, -2],
        [-2, -2, -2]], dtype=torch.int32)


In [ ]:
c = torch.tensor([1,-2,3,-4])
#absolute value of these making these positive
print(torch.abs(c))
#making negative
print(torch.neg(c))

tensor([1, 2, 3, 4])
tensor([-1,  2, -3,  4])


In [ ]:
d = torch.tensor([0.2,1.9,2.1,4.5,])
#clamp
print(torch.clamp(d,min=2,max=3))

tensor([2.0000, 2.0000, 2.1000, 3.0000])


In [ ]:
e = torch.randint(size=(2,3),low = 0 ,high = 10)
e

tensor([[7, 9, 9],
        [7, 2, 9]])

In [ ]:
#sum of whole matrix
print(torch.sum(e))
print(torch.max(e))
print(torch.min(e))

tensor(43)
tensor(9)
tensor(2)


In [ ]:
#dot product
f = torch.tensor([1,2,3,4])
torch.dot(c,f)

tensor(-10)

In [ ]:
#transpose
print(v.T)

tensor([[0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)


In [ ]:
j = torch.tensor([[1,-2,3],[5,-7,-8]],dtype=float)
print(j)

tensor([[ 1., -2.,  3.],
        [ 5., -7., -8.]], dtype=torch.float64)


In [ ]:
torch.sigmoid(j)

tensor([[7.3106e-01, 1.1920e-01, 9.5257e-01],
        [9.9331e-01, 9.1105e-04, 3.3535e-04]], dtype=torch.float64)

In [ ]:
torch.softmax(j,dim=0)

tensor([[1.7986e-02, 9.9331e-01, 9.9998e-01],
        [9.8201e-01, 6.6929e-03, 1.6701e-05]], dtype=torch.float64)

In [ ]:
torch.relu(j)

tensor([[1., 0., 3.],
        [5., 0., 0.]], dtype=torch.float64)

In [ ]:
j = j.to(torch.float32)
print(j)

tensor([[ 1., -2.,  3.],
        [ 5., -7., -8.]])


In [ ]:
# for inplace , to set the permanent value just add (_) underscore after command
j.add_(e)

tensor([[ 8.,  7., 12.],
        [12., -5.,  1.]])

In [ ]:
j

tensor([[ 8.,  7., 12.],
        [12., -5.,  1.]])

In [ ]:
torch.relu_(j)

tensor([[ 8.,  7., 12.],
        [12.,  0.,  1.]])

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9752, 0.0903, 0.5273],
        [0.6794, 0.2639, 0.3906]])

In [ ]:
b=a
b

tensor([[0.9752, 0.0903, 0.5273],
        [0.6794, 0.2639, 0.3906]])

In [ ]:
a[0][0] = 0
a

tensor([[0.0000, 0.0903, 0.5273],
        [0.6794, 0.2639, 0.3906]])

In [ ]:
#now it will print same in b also which is the problem , so if we dont want to copy changes of a to b , --> we do clone
print(b)
print(id(a))
print(id(b))

tensor([[0.0000, 0.0903, 0.5273],
        [0.6794, 0.2639, 0.3906]])
132345893006432
132345893006432


In [ ]:
a[0][0] = 10
a

tensor([[10.0000,  0.0903,  0.5273],
        [ 0.6794,  0.2639,  0.3906]])

In [ ]:
#clone
b = a.clone()
print(b)
print(id(a))
print(id(b))

tensor([[1.0000, 4.0903, 4.5273],
        [4.6794, 4.2639, 4.3906]])
132345893006432
132345544651744


In [ ]:
#reshaping
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.1661, 0.2636, 0.0442, 0.4884],
         [0.7965, 0.7432, 0.9697, 0.0609],
         [0.4385, 0.9868, 0.5819, 0.3590]],

        [[0.0497, 0.7327, 0.8796, 0.9009],
         [0.9186, 0.5979, 0.8564, 0.3741],
         [0.9061, 0.4572, 0.3969, 0.2515]]])

In [ ]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
#unsqueez , is 1 added at 0th place then it is for batch , like we can send multiple image in 1 batch
b.unsqueeze(0).shape

torch.Size([1, 2, 3, 4])

In [ ]:
#unsqueeze , removing dimension
b.squeeze(0).shape

torch.Size([2, 3, 4])

In [ ]:
# TENSOR TO NUMPY , NUMPY TO TENSOR
import numpy as np
a = torch.tensor([1,2,3])
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
torch.from_numpy(b)

tensor([1, 2, 3])