In [3]:
import torch 
import torch.nn as nn

In [7]:
class model(nn.Module) :
    def __init__(self,num_features) :
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features) :
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out
    

In [8]:
#CREATING FAKE DATASET
features = torch.rand(10,5)

#create model
Model = model(features.shape[1])

#call model for forward pass 
Model(features)

tensor([[0.4869],
        [0.5678],
        [0.5710],
        [0.5412],
        [0.5260],
        [0.5090],
        [0.5217],
        [0.5433],
        [0.4560],
        [0.5925]], grad_fn=<SigmoidBackward0>)

In [9]:
Model.linear.weight

Parameter containing:
tensor([[-0.2725, -0.1032, -0.2035,  0.3001,  0.0999]], requires_grad=True)

In [10]:
Model.linear.bias

Parameter containing:
tensor([0.2801], requires_grad=True)

In [11]:
!pip install torchinfo

In [13]:
from torchinfo import summary
summary(Model,(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [125]:
class model1(nn.Module) :
    def __init__(self,num_features) :
        super().__init__()
        #self.linear2 = nn.Linear(num_features,3)
        #self.relu = nn.ReLU()
        #self.linear3 = nn.Linear(3,1)
        #self.sigmoid = nn.Sigmoid()
    #USING SEQUENTIAL LOOP HERE
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid() )
            
    def forward(self,features) :
        #out = self.linear2(features)
        #out = self.relu(out)
        #out = self.linear3(out)
        out = self.network(features)
        
        return out
    

In [126]:
#CREATING FAKE DATASET
features = torch.rand(10,5)

#create model
Model1 = model1(features.shape[1])

#call model for forward pass 
Model1(features)

tensor([[0.3817],
        [0.3965],
        [0.4175],
        [0.4215],
        [0.3874],
        [0.4237],
        [0.4611],
        [0.4110],
        [0.3725],
        [0.4239]], grad_fn=<SigmoidBackward0>)

In [129]:
summary(Model1,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
model1                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00